name: anomalias_macro
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy<2.0
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - plotly
  - holidays=0.24
  - streamlit
  - ipykernel
  - jupyterlab
  - pip
  - pip:
      - prophet==1.1.4
      - cmdstanpy==1.0.8
      - stanio==0.3.0
